version: '2'

services:
  nginx:
    build: nginx
    container_name: test-project-nginx
    networks:
      - test-project-net
    ports:
      - 16326:80
  fpm:
    build: fpm
    tty: true
    container_name: test-project-fpm-1
    volumes:
      - ../:/home/eyurkin/source
    networks:
      - test-project-net
    environment:
      - LOGSTASH_PATH=elk:5044
      - LOGSTASH_ENABLED=true
      - APP_LOG_LEVEL=error
      - APP_KEY=9SroAE30Xqf1RktqG3gjFGscr4vfwAuq
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=test_project
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_COLLECTOR_HOST=jaeger
  mysql:
    image: tattoor/mysql_lr
    container_name: test-project-mysql
    networks:
      - test-project-net
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=test_project
    volumes:
      - ./varlibmysql:/var/lib/mysql
    ports:
      - 16324:3306
  redis:
    image: redis:3.2-alpine
    container_name: test-project-redis
    restart: always
    networks:
      - test-project-net
    ports:
      - 16323:6379
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    container_name: test-project-jaeger
#    restart: always
#    ports:
#      - 16322:16686
#    networks:
#      - test-project-net
#  elk:
#    image: sebp/elk
#    container_name: test-project-elk
#    restart: always
#    networks:
#      - test-project-net
#    ports:
#      - 16320:5601
#      - 16321:9200
networks:
  test-project-net:
    driver: bridge